// This file is auto-generated. Do not edit manually.
export const TEMPLATES: Record<string, string> = {
  "console_coverage_report.txt":
    '-------------\nDiff Coverage\nDiff: {{ diff_name }}\n-------------\n{% if src_stats %}\n{% for src_path, stats in src_stats|dictsort %}\n{% if stats.percent_covered < 100 %}\n{{ src_path }} ({{ stats.percent_covered|round(1) }}%): Missing lines {{ stats.violation_lines|join(\',\') }}\n{% else %}\n{{ src_path }} (100%)\n{% endif %}\n{% endfor %}\n-------------\nTotal:   {{ total_num_lines }} {{ "line" if total_num_lines == 1 else "lines" }}\n\nMissing: {{ total_num_violations }} {{ "line" if total_num_violations == 1 else "lines" }}\n\nCoverage: {{ total_percent_covered }}%\n-------------\n{% else %}\nNo lines with coverage information in this diff.\n-------------\n{% endif %}\n\n{% include \'snippet_content.txt\' %}\n',
  "console_quality_report.txt":
    '-------------\nDiff Quality\nQuality Report: {{ report_name }}\nDiff: {{ diff_name }}\n-------------\n{% if src_stats %}\n{% for src_path, stats in src_stats|dictsort %}\n{% if stats.percent_covered < 100 %}\n{{ src_path }} ({{ stats.percent_covered|round(1) }}%):\n{% for line, message in stats.violations %}\n{{ src_path }}:{{ line }}: {{ message }}\n{% endfor %}\n{% else %}\n{{ src_path }} (100%)\n{% endif %}\n{% endfor %}\n-------------\nTotal:   {{ total_num_lines }} {{ "line" if total_num_lines == 1 else "lines" }}\n\nViolations: {{ total_num_violations }} {{ "line" if total_num_violations == 1 else "lines" }}\n\n% Quality: {{ total_percent_covered }}%\n-------------\n{% else %}\nNo lines with quality information in this diff.\n-------------\n{% endif %}\n',
  "external_style.css":
    ".src-snippet { margin-top: 2em; }\r\n.src-name { font-weight: bold; }\r\n.snippets {\r\n    border-top: 1px solid #bdbdbd;\r\n    border-bottom: 1px solid #bdbdbd;\r\n}\r\n{{ snippet_style }}\r\n",
  "github_coverage_annotations.txt":
    '{% if src_stats %}\r\n{% for src_path, stats in src_stats|dictsort %}\r\n{% if stats.percent_covered < 100 %}\r\n{% for line in stats.violation_lines %}\r\n{% set splitLines = line.split("-") %}\r\n::{{ annotations_type }} file={{ src_path }},line={{ splitLines[0] }}{% if splitLines[1] %},endLine={{ splitLines[1] }}{% endif %},title=Missing Coverage::Line {{ line }} missing coverage\r\n{% endfor %}\r\n{% endif %}\r\n{% endfor %}\r\n{% endif %}\r\n',
  "html_coverage_report.html":
    '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html>\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n    <title>Diff Coverage</title>\n    {% include \'snippet_style.html\' %}\n  </head>\n  <body>\n    <h1>Diff Coverage</h1>\n    <p>Diff: {{ diff_name }}</p>\n    {% if src_stats %}\n    <ul>\n      <li><b>Total</b>: {{ total_num_lines }} {{ "line" if total_num_lines == 1 else "lines" }}</li>\n      <li>\n        <b>Missing</b>: {{ total_num_violations }} {{ "line" if total_num_violations == 1 else\n        "lines" }}\n      </li>\n      <li><b>Coverage</b>: {{ total_percent_covered }}%</li>\n    </ul>\n    <table border="1">\n      <tr>\n        <th>Source File</th>\n        <th>Diff Coverage (%)</th>\n        <th>Missing Lines</th>\n      </tr>\n      {% for src_path, stats in src_stats|dictsort %} {% if stats.percent_covered < 100 %}\n      <tr>\n        <td>{{ src_path }}</td>\n        <td>{{ stats.percent_covered|round(1) }}%</td>\n        <td>{{ stats.violation_lines|join(\',\') }}</td>\n      </tr>\n      {% else %}\n      <tr>\n        <td>{{ src_path }}</td>\n        <td>100%</td>\n        <td>&nbsp;</td>\n      </tr>\n      {% endif %} {% endfor %}\n    </table>\n    {% else %}\n    <p>No lines with coverage information in this diff.</p>\n    {% endif %} {% include \'snippet_content.html\' %}\n  </body>\n</html>\n',
  "html_quality_report.html":
    '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html>\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n    <title>Diff Quality</title>\n    {% include \'snippet_style.html\' %}\n  </head>\n  <body>\n    <h1>Diff Quality</h1>\n    <p>Quality Report: {{ report_name }}</p>\n    <p>Diff: {{ diff_name }}</p>\n    {% if src_stats %}\n    <table border="1">\n      <tr>\n        <th>Source File</th>\n        <th>Diff Quality (%)</th>\n        <th>Lines in violation</th>\n      </tr>\n      {% for src_path, stats in src_stats|dictsort %} {% if stats.percent_covered < 100 %}\n      <tr>\n        <td>{{ src_path }}</td>\n        <td>{{ stats.percent_covered|round(1) }}%</td>\n        <td>\n          <ul>\n            {% for line, message in stats.violations %}\n            <li>{{ line }}: {{ message }}</li>\n            {% endfor %}\n          </ul>\n        </td>\n      </tr>\n      {% else %}\n      <tr>\n        <td>{{ src_path }}</td>\n        <td>100%</td>\n        <td>&nbsp;</td>\n      </tr>\n      {% endif %} {% endfor %}\n    </table>\n    <ul>\n      <li><b>Total</b>: {{ total_num_lines }} {{ "line" if total_num_lines == 1 else "lines" }}</li>\n      <li>\n        <b>Violation</b>: {{ total_num_violations }} {{ "line" if total_num_violations == 1 else\n        "lines" }}\n      </li>\n      <li><b>% Quality</b>: {{ total_percent_covered }}%</li>\n    </ul>\n    {% else %}\n    <p>No lines with quality information in this diff.</p>\n    {% endif %} {% include \'snippet_content.html\' %}\n  </body>\n</html>\n',
  "markdown_coverage_report.md":
    '# Diff Coverage\n\n## Diff: {{ diff_name }}\n\n{% if src_stats %}\n{% for src_path, stats in src_stats|dictsort %}\n{% if stats.percent_covered < 100 %}\n\n- {{ src_path | replace(".", "&#46;") }} ({{ stats.percent_covered|round(1) }}%): Missing lines {{ stats.violation_lines|join(\',\') }}\n  {% else %}\n- {{ src_path | replace(".", "&#46;") }} (100%)\n  {% endif %}\n  {% endfor %}\n\n## Summary\n\n- **Total**: {{ total_num_lines }} {% trans count=total_num_lines %}line{% pluralize %}lines{% endtrans %}\n\n- **Missing**: {{ total_num_violations }} {% trans count=total_num_violations %}line{% pluralize %}lines{% endtrans %}\n\n- **Coverage**: {{ total_percent_covered }}%\n\n{% else %}\nNo lines with coverage information in this diff.\n{% endif %}\n\n{% include \'snippet_content.md\' %}\n',
  "markdown_quality_report.md":
    "# Diff Quality\n\n## Quality Report: {{ report_name }}\n\n## Diff: {{ diff_name }}\n\n{% if src_stats %}\n{% for src_path, stats in src_stats|dictsort %}\n{% if stats.percent_covered < 100 %}\n\n- {{ src_path }} ({{ stats.percent_covered|round(1) }}%):\n  {% for line, message in stats.violations %}\n  - {{ src_path }}:{{ line }}: {{ message }}\n    {% endfor %}\n    {% else %}\n- {{ src_path }} (100%)\n  {% endif %}\n  {% endfor %}\n\n- **Total**: {{ total_num_lines }} {% trans count=total_num_lines %}line{% pluralize %}lines{% endtrans %}\n\n- **Violations**: {{ total_num_violations }} {% trans count=total_num_violations %}line{% pluralize %}lines{% endtrans %}\n\n- **% Quality**: {{ total_percent_covered }}%\n\n{% else %}\nNo lines with quality information in this diff.\n{% endif %}\n",
  "snippet_content.html":
    '{% for src_path, stats in src_stats|dictsort %} {% if stats.snippets_html.length > 0 %}\n<div class="src-snippet">\n  <div class="src-name">{{ src_path }}</div>\n  <div class="snippets">\n    {% for snippet in stats.snippets_html %} {{ snippet | safe }} {% endfor %}\n  </div>\n</div>\n{% endif %} {% endfor %}\n',
  "snippet_content.md":
    '{% for src_path, stats in src_stats|dictsort %}\n{% if stats.snippets_markdown %}\n\n## {{ src_path | replace(".", "&#46;") }}\n\n{% for snippet in stats.snippets_markdown %}\n\n{{ snippet }}\n\n---\n\n{% endfor %}\n\n{% endif %}\n{% endfor %}\n',
  "snippet_content.txt":
    "{% for src_path, stats in src_stats|dictsort %}\n{% if stats.snippets_terminal.length > 0 %}\n--- {{ src_path }} ---\n{% for snippet in stats.snippets_terminal %}\n\n{{ snippet }}\n\n\n{% endfor %}\n{% endif %}\n{% endfor %}\n",
  "snippet_style.html":
    '{% if snippet_style %} {% if css_url %}\n<link rel="stylesheet" href="{{ css_url }}" />\n{% else %}\n<style>\n  .src-snippet { margin-top: 2em; }\n  .src-name { font-weight: bold; }\n  .snippets {\n      border-top: 1px solid #bdbdbd;\n      border-bottom: 1px solid #bdbdbd;\n  }\n  {{ snippet_style }}\n</style>\n{% endif %} {% endif %}\n',
};
